name: Hello World Workflow

on:
  push:
    branches: [ sarah-task1 ]
  pull_request:
    branches: [ sarah-task1 ]

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Print Hello World
        run: echo "Hello World from GitHub Actions on branch sarah-task1!"
